### ISSUE TITLE
Some question in using electron-store

### ISSUE THREAD

**Issue by flytam** [alexbrazier/package-bundle#6]
I feel sorry that ask you this question in this issue butI am in a hurry.I use electron-store with some error in package electron-store.I see you said that
```
I got this working by adding electron-store to externals. externals: ['electron-store']

@nicolabortignon Using the boilerplate you can change: import { dependencies as externals } from './app/package.json'; to import { dependencies as externals } from './package.json'; to make it work
```
I use the boilerplate ,and i did as you said.But it seems not ok.How can i do?Thanks a lot!

**Comment by flytam** [comment]
hello？

**Comment by alexbrazier** [comment]
@673800357 I don't really remember the issue tbh as it was quite a while ago, so I can't really help more than my comment. I would suggest opening an issue in the electron-store or webpack repo if you can't get it working.

**Comment by flytam** [comment]
[link](https://github.com/sindresorhus/electron-store/issues/3#issuecomment-326749818)
Here are your answer. I has opened the similar issue, but the  electron-store's staff let me see the link which you has answered. Could you show me the key code for package?Thanks

**Comment by flytam** [comment]
i have fixed it [link](https://github.com/chentsulin/electron-react-boilerplate/issues/1323). Thanks
