### ISSUE TITLE
Allow use of private registries

### ISSUE THREAD

**Issue by stephandrab** [alexbrazier/package-bundle#8]
I would like to use `package-bundle` together with a private registry, frankly the npm registry `https://registry.npmjs.org/` is hardcoded :-/

I would suggest to:
- either to interpret the `.npmrc`
- or introduce a `--registry` cli parameter
- or both :-)

to configure the registry being used.

**Comment by alexbrazier** [comment]
@stephandrab Good idea! I would be happy to merge a PR for this, or I could potentially look into it sometime next week.

**Comment by luisdavim** [comment]
this would be great.
